spring:
  redis:
    url: redis://localhost:6379
  kafka:
    consumer:
      properties.spring.json.trusted.packages: com.fastcampus.sns.model.event
      bootstrap-servers: 127.0.0.1:9092
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    listener:
      ack-mode: manual
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    #    properties:
    #      security.protocol: SASL_SSL
    #      sasl.mechanism: SCRAM-SHA-256
    topic:
      alarm: sns-alarm
  
  
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 2

  datasource:
    hikari:
      maximum-pool-size: 6
    url: jdbc:postgresql://ec2-3-220-207-90.compute-1.amazonaws.com/ddq1b52jfbf7p7
    username: mdgdlxfmdsomad
    password: 2807e7e5699cdf03ba1260e88fb9f090cd52d34915d318777ca96674380466b7
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  token.expired-time-ms: 2592000000
logging:
  level:
    org.hibernate.sql:

#  config: classpath:logback-spring.xml